name = "family-hub-api"
main = "src/index.ts"
compatibility_date = "2024-11-22"
account_id = "e4098995274eda5a57ffc583d058dcf0"

[observability]
enabled = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "family-hub-db"
database_id = "07408c85-d949-4908-aeba-5dd307bbbbfe" # Tạo sau bằng: wrangler d1 create family-hub-db

# R2 Storage
[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "family-hub-receipts"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-secret-key-change-me"

# Production secrets (set via: wrangler secret put SECRET_NAME)
# SMTP_PASSWORD
# EXCHANGE_RATE_API_KEY
